name: Continous build & release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: Builds and releases new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Initial release
          draft: false
          prerelease: false
      - name: Setup graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.3.0"
          java-version: "java11"
          native-image: "true"
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output
        name: Download the pico-cli jar
        with:
          url: "https://search.maven.org/remotecontent?filepath=info/picocli/picocli/4.5.2/picocli-4.5.2.jar"
          target: build/
      - name: Build image
        run: ${GRAALVM_HOME}/bin/native-image -cp ./build/picocli-4.5.2.jar --static -jar ./build/libs/desktop-notifier-1.0-SNAPSHOT-all.jar desktop-notifier
      - name: Upload jar binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/desktop-notifier-1.0-SNAPSHOT-all.jar
          asset_name: desktop-notifier.jar
          asset_content_type: application/zip
      - name: Upload native binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./desktop-notifier
          asset_name: desktop-notifier
          asset_content_type: application/binary
